//const kParseApplicationId = "kQJzUzTqahVhZgIFkhYAEhk0anSpOsPwJPyU4yh7";
//const kParseRestApiKey = "KqQ3HCfWuBIqldAUBbUSLdlDt6KmmhmarhzRU84Y";
//const baseUrl = "https://parseapi.back4app.com/classes/";
const kParseApplicationId = "myAppId";
const kParseRestApiKey = "myRestKey";
const kParseServerUrl = "https://967e5e22bf60.ngrok.io/parse";
const baseUrl = "https://967e5e22bf60.ngrok.io/parse/classes/";
const kParseClientKey = "myClientKey";
const kLiveQueryUrl = "https://967e5e22bf60.ngrok.io/"; //change this
const kParseMasterKey = "myMasterKey";